# Generated by Django 5.1.3 on 2026-06-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SketchyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initials', models.CharField(max_length=3)),
                ('points', models.IntegerField()),
                ('player_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-points', 'created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('player_id', ''), _negated=True), fields=('player_id',), name='sketchy_unique_nonblank_player_id')],
            },
        ),
    ]
