# Generated by Django 5.0.6 on 2024-11-07 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metaguess', '0003_appvisit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppVisit',
        ),
    ]
