# Generated by Django 5.1.3 on 2026-06-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricochet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ricochetscore',
            name='player_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
