# Generated by Django 5.1.3 on 2026-06-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricochet', '0002_ricochetscore_player_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ricochetscore',
            constraint=models.UniqueConstraint(condition=models.Q(('player_id', ''), _negated=True), fields=('player_id',), name='ricochet_unique_nonblank_player_id'),
        ),
    ]
